const symfonyPasswordComparator = require('./comparator');

test('should compare successfully a hash generated by the symfony 3.4 encoder', async () => {
    const testEncoded = '$2y$06$9Eg8rTTeLqPjNTlm9EC9Y.E7aMgfud6YhjM7DEPYsHJaZTGYVA.za';

    const result = await symfonyPasswordComparator('12345678', testEncoded);
    expect(result).toBeTruthy();
});